site_name: Agent
theme:
  name: material  # 使用最流行的 Material 主题
  language: zh    # 设置为中文
  features:
    - navigation.tabs  # 开启顶部导航栏
    - search.suggest   # 开启搜索建议

nav:
  - 首页: index.md
  - Rag: 
    - 文档切分: rag/chunk.md
